version: '3.7'

services:
  mlog_csv_service:
    container_name: mlog_csv_service_container
    image: mlog_csv_service
    build:
      context: ./csv_service/
      dockerfile: Dockerfile
    ports:
      - $CSV_SERVICE_PORT:$CSV_SERVICE_PORT
    environment:
      - SECRET_KEY
      - DEBUG
      - CSV_SERVICE_PORT

  mlog_payment_log_analyzer:
    container_name: mlog_payment_log_analyzer_container
    image: mlog_payment_log_analyzer
    build:
      context: ./payment_log_analyzer/
      dockerfile: Dockerfile
    ports:
      - $PAYMENT_LOG_ANALYZER_PORT:$PAYMENT_LOG_ANALYZER_PORT
    environment:
      - SECRET_KEY
      - DEBUG
      - PAYMENT_LOG_ANALYZER_PORT
      - SEARCH_SERVICE_URL
      - CSV_SERVICE_URL
    depends_on:
      - mlog_csv_service
      - mlog_search_service

  mlog_search_service:
    container_name: mlog_search_service_container
    image: mlog_search_service
    build:
      context: ./search_service/
      dockerfile: Dockerfile
    ports:
      - $SEARCH_SERVICE_PORT:$SEARCH_SERVICE_PORT
    environment:
      - SECRET_KEY
      - DEBUG
      - SEARCH_SERVICE_PORT
      - ELASTIC_SEARCH_URL
      - ELASTIC_AUTH_USERNAME
      - ELASTIC_AUTH_PASSWORD

  mlog_view_service:
    container_name: mlog_view_service_container
    image: mlog_view_service
    build:
      context: ./view_service/
      dockerfile: Dockerfile
    ports:
      - $VIEW_SERVICE_PORT:$VIEW_SERVICE_PORT
    environment:
      - VIEW_SERVICE_PORT
      - VUE_APP_ANALYZER_URL
    depends_on:
      - mlog_payment_log_analyzer
