version: '3.7'

services:
  mlog_csv_service:
    container_name: mlog_csv_service_container
    image: mlog_csv_service
    build:
      context: ./csv_service/
      dockerfile: Dockerfile
    ports:
      - $CSV_SERVICE_PORT:$CSV_SERVICE_PORT
    env_file:
      - csv_service/.env
    environment:
      - CSV_SERVICE_PORT
    volumes:
      - ./csv_service:/csv_service

  mlog_cart_log_analyzer:
    container_name: mlog_payment_log_analyzer_container
    image: mlog_payment_log_analyzer
    build:
      context: ./payment_log_analyzer/
      dockerfile: Dockerfile
    ports:
      - $PAYMENT_LOG_ANALYZER_PORT:$PAYMENT_LOG_ANALYZER_PORT
    env_file:
      - payment_log_analyzer/.env
    environment:
      - PAYMENT_LOG_ANALYZER_PORT
    volumes:
      - ./payment_log_analyzer:/payment_log_analyzer

  mlog_search_service:
    container_name: mlog_search_service_container
    image: mlog_search_service
    build:
      context: ./search_service/
      dockerfile: Dockerfile
    ports:
      - $SEARCH_SERVICE_PORT:$SEARCH_SERVICE_PORT
    env_file:
      - search_service/.env
    environment:
      - SEARCH_SERVICE_PORT
    volumes:
      - ./search_service:/search_service