# ENV
export SECRET_KEY=CHANGEME
export DEBUG=true

# Ports
export SEARCH_SERVICE_PORT=8081
export CSV_SERVICE_PORT=8082
export PAYMENT_LOG_ANALYZER_PORT=8083
export VIEW_SERVICE_PORT=8084

# URLs
export YOUR_IP=[INSERT YOUR IP HERE]
export ELASTIC_SEARCH_URL=http://$YOUR_IP:9200
export SEARCH_SERVICE_URL=http://$YOUR_IP:$SEARCH_SERVICE_PORT
export CSV_SERVICE_URL=http://$YOUR_IP:$CSV_SERVICE_PORT
export VUE_APP_ANALYZER_URL=http://$YOUR_IP:$PAYMENT_LOG_ANALYZER_PORT

# Auth
export ELASTIC_AUTH_USERNAME=elastic
export ELASTIC_AUTH_PASSWORD=changeme
