# ENV
export SECRET_KEY=CHANGEME
export DEBUG=true

# Ports
export SEARCH_SERVICE_PORT=8081
export CSV_SERVICE_PORT=8082
export PAYMENT_LOG_ANALYZER_PORT=8083

# URLs
export ELASTIC_SEARCH_URL=http://[INSERT YOUR IP HERE]:9200
export SEARCH_SERVICE_URL=http://[INSERT YOUR IP HERE]:$SEARCH_SERVICE_PORT
export CSV_SERVICE_URL=http://[INSERT YOUR IP HERE]:$CSV_SERVICE_PORT

# Auth
export ELASTIC_AUTH_USERNAME=elastic
export ELASTIC_AUTH_PASSWORD=changeme
